FROM postgres:14.2-bullseye

# Install Python
RUN apt update -y
RUN apt install python3 -y
RUN apt install python3-pip -y
RUN apt install libpq-dev python3-dev

WORKDIR /setups
COPY . .
RUN pip3 install -r requirements.txt
